version: "3.9"

services:
  geth:
    image: ethereum/client-go:${GETH_TAG}
    stop_grace_period: 8m
    container_name: geth-${NETWORK}
    volumes:
      - type: bind
        source: ${PWD}/datadirs/${NETWORK}/geth
        target: /data
      - ${PWD}/.config/l1-jwt-secret.txt:/config/jwt-secret.txt
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    command: >
      --${NETWORK}
      --datadir=/data
      --ipcdisable
      --http
      --http.addr=0.0.0.0
      --ws
      --ws.addr=0.0.0.0
      --authrpc.jwtsecret=/config/jwt-secret.txt
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts=*
  lighthouse:
    depends_on:
      - geth
    image: sigp/lighthouse:${LIGHTHOUSE_TAG}
    container_name: lighthouse-${NETWORK}
    volumes:
      - type: bind
        source: ${PWD}/datadirs/${NETWORK}/lighthouse
        target: /data
      - ${PWD}/.config/l1-jwt-secret.txt:/config/jwt-secret.txt
    ports:
      - 9000:9000
      - 443:443
    command: >
      lighthouse bn
      --network=${NETWORK}
      --datadir=/data
      --execution-endpoint=http://geth:8551
      --execution-jwt=/config/jwt-secret.txt
      --disable-deposit-contract-sync
      --checkpoint-sync-url=${CHECKPOINT_SYNC_URL}